; JUST IMPLEMENT MAINROUTINE AND 
;CALL MAINEXIT TO RETURN AND CHANGE STUFF
;JP MAINEXIT TO RETURN
;BEF_SP_CHANGE ALSO ARE JUMPED AND SHOULD JP TO DO_SP_CHANGE
;BEF_SP_CHANGE:  JP DO_SP_CHANGE
;EX_BF_SP_CHNG FOR EXITING
;EX_BF_SP_CHNG: JP EX_DO_SP_CHNG

		GLOBAL LASTVAR 

		@DEVMMU EQU $00;
                @DEVSER EQU $20
                @DEVSYS EQU $E1
                @DEVSND EQU $40 ;FOR SN76489
		@DEV376 EQU $30
		@DEVKBI EQU $48

		@FONT_ADDR EQU $00	;FONT ALREADY LOADED 
		@VIDPG 	EQU $C0		;WAS 8 DPVRAM START PAGE TOTAL 8 64KB ON 2 BUFFERS 0 AND 1

                @MMU_PORT EQU DEVMMU
                @MMU_READ_PORT EQU DEVMMU

;MAIN ENTRY FOR LOAD ISSUED FROM AMSTRAD
@MENTRY:        NOP
		DI
                PUSH AF		;save old regs on old sp
                PUSH BC
                PUSH DE
                PUSH HL		
                PUSH IX
                PUSH IY	

		IN A,(DEVSYS)           ;current system should be saved and
		LD D,A			;SAVE TO D
                LD A,$F0		;HIGH NIBBLE TO KEEP THE VIDEO SCREEN, LOW NIBBLE TO SET SYSTEM
                OUT (DEVSYS),A          ;SET NEW SYSTEM  0 AS BOOTLOADER 				
		LD B,MYRAMBANK		;READ OLD page  OF our ram bank
                SLA B   ;PUT IT ON HIGH BYTES
                SLA B
                SLA B
                SLA B
                SLA B  
                LD C,MMU_READ_PORT              
		IN A,(C)		
		LD E,A 		;SAVE TO E
		LD A,$7F	;LAST RAM PAGE IS OUR VAR PAGE ON BANK 7
		LD B,MYRAMBANK
		SLA B 
		SLA B 
		SLA B 
		SLA B 
		SLA B 
		LD C,DEVMMU
		OUT (C),A	;CANT USE MMU SET CALL HERE SAFELY
		CALL CHECKID
		JR C,SKIP1
		LD A,E 		;RESTORE A AS OLD PAGE ON 7
		LD (OLDBNK7),A  ;SAVE AS VAR
                LD A,D 		
		LD (OLDSYS),A   ;SAVE SYS VAR	
		;CALL PRINT_A				
		SCF
		CCF
SKIP1:		JP BEF_SP_CHANGE;IF CF THEN VARS ALREADY THERE
@DO_SP_CHANGE:	LD HL,0
		ADD HL,SP 	;HL HAS THE SP
		LD (OLDSP),HL		
		LD SP,BLSTACKP	;RAM TOP
                JP MAINROUTINE

@MAINEXIT:      LD HL,(OLDSP)		
		LD SP,HL	;SP RESTORED VARS NO LONGER NEEDED
		JP EX_BF_SP_CHNG
@EX_DO_SP_CHNG:	LD A,(OLDSYS) 
		LD D, A
		;call PRINT_A
		LD A,(OLDBNK7)
		LD B,MYRAMBANK
		SLA B 
		SLA B 
		SLA B 
		SLA B 
		SLA B 		   
		LD C,DEVMMU
		OUT (C),A       ;WE CAN'T USE CALL HERE SAFELY
		LD A,D 		 
                OUT (DEVSYS),A          ;SET SYSTEM BACK		
                POP IY
                POP IX
                POP HL
                POP DE
                POP BC
                POP AF
		EI
                RET


include VARS_CHK.Z80
