library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use work.defs_pkg.ALL; -- Import constants for Z80 clock selection

-- Note: In a real implementation for the GW5A FPGA, the frequencies 
-- (40M, 20M, 16M, 12M, 8M, 4M, 2M) must be generated using a vendor-specific 
-- PLL/MMCM IP core (like GW_PLLVR) from the 50MHz CLK_IN.

entity Clock_Manager is
    port (
        CLK_IN              : in  std_logic;                                   -- 50MHz Main FPGA Clock Input (CONFIRMED)
        RST_N               : in  std_logic;                                   -- Global Reset (Active Low)
        Z80_CLK_SEL         : in  std_logic_vector(7 downto 0);                -- Z80 Clock Selection Register
        
        -- System Outputs
        CLK_Z80             : out std_logic;                                   -- Final Selected Z80 Clock (2/4/8/10/12/16/20 MHz)
        CLK_PIXEL           : out std_logic;                                   -- DVI/HDMI Pixel Clock (40 MHz)
        CLK_SN76489         : out std_logic;                                   -- Audio Clock 1 (4 MHz)
        CLK_AY38912         : out std_logic;                                   -- Audio Clock 2 (2 MHz)
        PLL_LOCKED          : out std_logic                                    -- Indicates PLL has achieved stability (Active High)
    );
end Clock_Manager;

architecture RTL of Clock_Manager is
    
    -- --- Internal signals from the Clock Manager IP (PLL) ---
    signal CLK_PIXEL_REF        : std_logic; -- 40 MHz Reference (clkout0)
    signal CLK_Z80_16M_REF      : std_logic; -- 16 MHz Reference (clkout1)
    signal CLK_Z80_12M_INT      : std_logic; -- 12 MHz (clkout2)
    signal PLL_LOCKED_INT       : std_logic; -- PLL LOCK status (lock)
    
    -- --- Signals generated by internal clock division from 40 MHz ---
    signal CLK_Z80_20M_INT      : std_logic := '0'; -- 20 MHz (40M / 2)
    signal CLK_Z80_10M_INT      : std_logic := '0'; -- 10 MHz (40M / 4)
    signal CLK_40M_DIV_COUNTER  : unsigned(1 downto 0) := (others => '0'); 
    
    -- --- Signals generated by internal clock division from 16 MHz ---
    signal CLK_Z80_8M_INT       : std_logic := '0'; -- 8 MHz (16M / 2)
    signal CLK_4M_INT           : std_logic := '0'; -- 4 MHz (16M / 4)
    signal CLK_2M_INT           : std_logic := '0'; -- 2 MHz (16M / 8)
    signal CLK_16M_DIV_COUNTER  : unsigned(2 downto 0) := (others => '0');
    
    -- Final selected Z80 clock before port output
    signal CLK_Z80_FINAL        : std_logic;
    

    -- Note: The control ports (RESET, POWERDOWN, CLKIN_RST, CLKOUT_RST) are 
    -- assumed to be configured as unused or tied off within the IP core 
    -- generation if they are not explicitly in the prototype.
    component Clocks_PLL 
        port (
            clkin           : in  std_logic;    -- 50MHz Input
            clkout0         : out std_logic;    -- 40 MHz
            clkout1         : out std_logic;    -- 16 MHz
            clkout2         : out std_logic;    -- 12 MHz
            lock            : out std_logic;    -- PLL Lock Status (Active High)
            mdclk           : in  std_logic     -- mDRP Clock (tied to CLK_IN)
        );
    end component;

begin
    
    -- 1. Clock IP Core Instantiation
    -- The instance name is chosen for clarity (u_PLL_Core).
    -- Ports are mapped exactly as defined in the IP core prototype.
    u_PLL_Core : Clocks_PLL
        port map (
            clkin           => CLK_IN,          -- Connects 50MHz external clock
            clkout0         => CLK_PIXEL_REF,   -- Internal 40 MHz signal
            clkout1         => CLK_Z80_16M_REF, -- Internal 16 MHz signal
            clkout2         => CLK_Z80_12M_INT, -- Internal 12 MHz signal
            lock            => PLL_LOCKED_INT,  -- Internal signal indicating lock
            mdclk           => CLK_IN           -- Tie unused DRP clock to main clock for stability
        );
    

    -- Map the internal lock signal to the output port
    PLL_LOCKED <= PLL_LOCKED_INT;

    -- 2. Division Chain from 40 MHz Reference (20MHz, 10MHz)
    process (CLK_PIXEL_REF, RST_N)
    begin
        if RST_N = '0' then
            CLK_40M_DIV_COUNTER <= (others => '0');
            CLK_Z80_20M_INT     <= '0';
            CLK_Z80_10M_INT     <= '0';
        elsif rising_edge(CLK_PIXEL_REF) then
            CLK_40M_DIV_COUNTER <= CLK_40M_DIV_COUNTER + 1;
            
            CLK_Z80_20M_INT     <= CLK_40M_DIV_COUNTER(0); -- 40M / 2 = 20MHz
            CLK_Z80_10M_INT     <= CLK_40M_DIV_COUNTER(1); -- 40M / 4 = 10MHz
        end if;
    end process;

    -- 3. Division Chain from 16 MHz Reference (8MHz, 4MHz, 2MHz)
    process (CLK_Z80_16M_REF, RST_N)
    begin
        if RST_N = '0' then
            CLK_16M_DIV_COUNTER <= (others => '0');
            CLK_Z80_8M_INT      <= '0';
            CLK_4M_INT          <= '0';
            CLK_2M_INT          <= '0';
        elsif rising_edge(CLK_Z80_16M_REF) then
            CLK_16M_DIV_COUNTER <= CLK_16M_DIV_COUNTER + 1;
            
            CLK_Z80_8M_INT      <= CLK_16M_DIV_COUNTER(0); -- 16M / 2 = 8MHz
            CLK_4M_INT          <= CLK_16M_DIV_COUNTER(1); -- 16M / 4 = 4MHz
            CLK_2M_INT          <= CLK_16M_DIV_COUNTER(2); -- 16M / 8 = 2MHz
        end if;
    end process;

    -- 4. Output Mapping for Fixed Clocks
    CLK_PIXEL     <= CLK_PIXEL_REF;     -- 40 MHz output
    CLK_SN76489   <= CLK_4M_INT;        -- 4 MHz Audio Clock (Derived from 16M)
    CLK_AY38912   <= CLK_2M_INT;        -- 2 MHz Audio Clock (Derived from 16M)
    
    -- 5. Z80 Clock Multiplexer
    with Z80_CLK_SEL(2 downto 0) select CLK_Z80_FINAL <=
        CLK_2M_INT          when SEL_2MHZ_C,  -- "000" (2 MHz)
        CLK_4M_INT          when SEL_4MHZ_C,  -- "001" (4 MHz)
        CLK_Z80_8M_INT      when SEL_8MHZ_C,  -- "010" (8 MHz)
        CLK_Z80_12M_INT     when SEL_12MHZ_C, -- "011" (12 MHz)
        CLK_Z80_16M_REF     when SEL_16MHZ_C, -- "100" (16 MHz)
        CLK_Z80_20M_INT     when SEL_20MHZ_C, -- "101" (20 MHz)
        CLK_Z80_10M_INT     when SEL_10MHZ_C, -- "110" (10 MHz)
        CLK_2M_INT          when others;      -- Default to 2 MHz if unmapped

    -- 6. Final Z80 Clock Output
    CLK_Z80 <= CLK_Z80_FINAL;

end RTL;